### ISSUE TITLE
Fail on start script

### ISSUE THREAD

**Issue by DevGhosti** [tbiens/icarus#7]
```py
Step 16/16 : CMD [ "python3", "/icarus/setup.py" ]
 ---> Using cache
 ---> 681ea09f8e58
Successfully built 681ea09f8e58
Successfully tagged icarus:latest
Traceback (most recent call last):
  File "/icarus/setup.py", line 125, in <module>
    curses.wrapper(main)
  File "/usr/local/lib/python3.8/curses/__init__.py", line 105, in wrapper
    return func(stdscr, *args, **kwds)
  File "/icarus/setup.py", line 96, in main
    cursewinder.addstr(17, 51, "Press P to change values.", curses.color_pair(2))
_curses.error: addwstr() returned ERR

```

**Comment by DevGhosti** [comment]
FIXED

INSTALL:
```ini
[Pre-install] sudo nano /etc/ssh/sshd_config
[NEXT] Change [#Port 22] TO [Port 1337] # or what ever ssh port you want besides 22-2222-2022
[FINALLY] sudo systemctl reload sshd
```
```
install
1. apt install tmux docker.io git screen -y
2. apt update && apt upgrade -y
3. git clone https://github.com/tbiens/icarus.git
4. cd icarus 
5. nano icarus.config #change this config with your API keys
6. nano setup.py # Remove line 96-99
7. THEN do | screen sudo bash start.sh
```

**Comment by tbiens** [comment]
Hey, glad you solved the problem. Most likely what was happening those lines 96-99 were drawing outside your screen size.
